version: "3.7"
name: basicecommerce

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db
    ports:
      - 5432:5432
    volumes:
      - pgdbvolume:/var/lib/postgresql/data

volumes:
  pgdbvolume:
    driver: local